export const FilterData = [
    {
        price : [1000,2000,3000,4000,5000,6000,7000,8000,9000,10000],
        color : ["pink","beige","yellow","red","ferozi","grey","black","green","blue",""],
        type : ['printed','embroidered'],
        fabric : ['karandi', 'lawn','linen','khaddar'],
        season : ['summer', 'winter','spring','eid special'],
    },
]



export const ProductData = [
    {
        id: 1,
        name : 'printed',
        price : '1000',
        category : 'print',
        fabric : 'linen',
        color : 'pink',
        type : 'printed',
        season : 'summer',
        rating : 4.1,
        img1 : '/assests/images/prints/printedPinkFront.jpg',
        img2 : '/assests/images/prints/printedPinkBack.jpg',
        img3 : '/assests/images/prints/printedPinkSide.jpg',
        img4 : '/assests/images/prints/printedPinkZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 2,
        name : 'printed',
        price : '2000',
        category : 'print',
        fabric : 'lawn',
        color : 'beige',
        type : 'embroidered',
        season : 'summer',
        rating : 3.4,
        img1 : '/assests/images/prints/printedBeigeFront.jpg',
        img2 : '/assests/images/prints/printedBeigeBack.jpg',
        img3 : '/assests/images/prints/printedBeigeSide.jpg',
        img4 : '/assests/images/prints/printedBeigeZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',
    },
    {
        id: 3,
        name : 'printed',
        price : '2000',
        category : 'print',
        fabric : 'khaddar',
        color : 'yellow',
        type : 'printed',
        season : 'spring',
        rating : 3.0,
        img1 : '/assests/images/prints/printedYellowFront.jpg',
        img2 : '/assests/images/prints/printedYellowBack.jpg',
        img3 : '/assests/images/prints/printedYellowSide.jpg',
        img4 : '/assests/images/prints/printedYellowZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 4,
        name : 'printed',
        price : '3000',
        category : 'print',
        fabric : 'lawn',
        color : 'red',
        type : 'embroidered',
        season : 'spring',
        rating : 4.6,
        img1 : '/assests/images/prints/printedRedFront.jpg',
        img2 : '/assests/images/prints/printedRedBack.jpg',
        img3 : '/assests/images/prints/printedRedSide.jpg',
        img4 : '/assests/images/prints/printedRedZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 5,
        name : 'printed',
        price : '4000',
        category : 'print',
        fabric : 'lawn',
        color : 'ferozi',
        type : 'printed',
        season : 'eid special',
        rating : 4.1,
        img1 : '/assests/images/prints/printedFeroziFront.jpg',
        img2 : '/assests/images/prints/printedFeroziBack.jpg',
        img3 : '/assests/images/prints/printedFeroziSide.jpg',
        img4 : '/assests/images/prints/printedFeroziZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 6,
        name : 'printed',
        price : '4000',
        category : 'print',
        fabric : 'karandi',
        color : 'grey',
        type : 'embroidered',
        season : 'winter',
        rating : 4.5,
        img1 : '/assests/images/prints/printedGreyFront.jpg',
        img2 : '/assests/images/prints/printedGreyBack.jpg',
        img3 : '/assests/images/prints/printedGreySide.jpg',
        img4 : '/assests/images/prints/printedGreyZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 7,
        name : 'printed',
        price : '5000',
        category : 'print',
        fabric : 'linen',
        color : 'black',
        type : 'printed',
        season : 'spring',
        rating : 2.5,
        img1 : '/assests/images/prints/printedBlackFront.jpg',
        img2 : '/assests/images/prints/printedBlackBack.jpg',
        img3 : '/assests/images/prints/printedBlackSide.jpg',
        img4 : '/assests/images/prints/printedBlackZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 8,
        name : 'printed',
        price : '5000',
        category : 'print',
        fabric : 'karandi',
        color : 'green',
        type : 'printed',
        season : 'winter',
        rating : 2.5,
        img1 : '/assests/images/prints/printedGreenFront.jpg',
        img2 : '/assests/images/prints/printedGreenBack.jpg',
        img3 : '/assests/images/prints/printedGreenZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 9,
        name : 'printed',
        price : '6000',
        category : 'print',
        fabric : 'lawn',
        color : 'black',
        type : 'embroidered',
        season : 'spring',
        rating : 4.8,
        img1 : '/assests/images/prints/printedBlackFront11.jpg',
        img2 : '/assests/images/prints/printedBlackBack11.jpg',
        img3 : '/assests/images/prints/printedBlackSide11.jpg',
        img4 : '/assests/images/prints/printedBlackZoom11.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 10,
        name : 'printed',
        price : '6000',
        category : 'print',
        fabric : 'kaddar',
        color : 'yellow',
        type : 'embroidered',
        season : 'spring',
        rating : 4.8,
        img1 : '/assests/images/prints/printedYellowFront11.jpg',
        img2 : '/assests/images/prints/printedYellowBack11.jpg',
        img3 : '/assests/images/prints/printedYellowSide11.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 11,
        name : 'printed',
        price : '6000',
        category : 'print',
        fabric : 'linen',
        color : 'pink',
        type : 'embroidered',
        season : 'spring',
        rating : 4.8,
        img1 : '/assests/images/prints/printedPinkFront11.jpg',
        img2 : '/assests/images/prints/printedPinkBack11.jpg',
        img3 : '/assests/images/prints/printedPinkSide11.jpg',
        img4 : '/assests/images/prints/printedPinkZoom11.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 12,
        name : 'printed',
        price : '4000',
        category : 'print',
        fabric : 'karandi',
        color : 'blue',
        type : 'printed',
        season : 'summer',
        rating : 4,
        img1 : '/assests/images/prints/printedBlueFront.jpg',
        img2 : '/assests/images/prints/printedBlueBack.jpg',
        img3 : '/assests/images/prints/printedBlueSide.jpg',
        img4 : '/assests/images/prints/printedBlueZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 13,
        name : 'printed',
        price : '4000',
        category : 'print',
        fabric : 'lawn',
        color : 'pink',
        type : 'embroidered',
        season : 'summer',
        rating : 4,
        img1 : '/assests/images/prints/printedPinkFront.jpg',
        img2 : '/assests/images/prints/printedPinkBack.jpg',
        img3 : '/assests/images/prints/printedPinkSide.jpg',
        img4 : '/assests/images/prints/printedPinkZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 14,
        name : 'printed',
        price : '6000',
        category : 'print',
        fabric : 'linen',
        color : 'beige',
        type : 'printed',
        season : 'eid special',
        rating : 4.8,
        img1 : '/assests/images/prints/printedBeigeFront.jpg',
        img2 : '/assests/images/prints/printedBeigeBack.jpg',
        img3 : '/assests/images/prints/printedBeigeSide.jpg',
        img4 : '/assests/images/prints/printedBeigeZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 15,
        name : 'printed',
        price : '6000',
        category : 'print',
        fabric : 'lawn',
        color : 'yellow',
        type : 'embroidered',
        season : 'eid special',
        rating : 4.6,
        img1 : '/assests/images/prints/printedYellowFront.jpg',
        img2 : '/assests/images/prints/printedYellowBack.jpg',
        img3 : '/assests/images/prints/printedYellowSide.jpg',
        img4 : '/assests/images/prints/printedYellowZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 16,
        name : 'printed',
        price : '7000',
        category : 'print',
        fabric : 'khaddar',
        color : 'red',
        type : 'embroidered',
        season : 'summer',
        rating : 4.1,
        img1 : '/assests/images/prints/printedRedFront.jpg',
        img2 : '/assests/images/prints/printedRedBack.jpg',
        img3 : '/assests/images/prints/printedRedSide.jpg',
        img4 : '/assests/images/prints/printedRedZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 17,
        name : 'printed',
        price : '4000',
        category : 'print',
        fabric : 'karandi',
        color : 'ferozi',
        type : 'embroidered',
        season : 'summer',
        rating : 4,
        img1 : '/assests/images/prints/printedFeroziFront.jpg',
        img2 : '/assests/images/prints/printedFeroziBack.jpg',
        img3 : '/assests/images/prints/printedFeroziSide.jpg',
        img4 : '/assests/images/prints/printedFeroziZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 18,
        name : 'printed',
        price : '8000',
        category : 'print',
        fabric : 'linen',
        color : 'grey',
        type : 'embroidered',
        season : 'winter',
        rating : 3.5,
        img1 : '/assests/images/prints/printedGreyFront.jpg',
        img2 : '/assests/images/prints/printedGreyBack.jpg',
        img3 : '/assests/images/prints/printedGreySide.jpg',
        img4 : '/assests/images/prints/printedGreyZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 19,
        name : 'printed',
        price : '10000',
        category : 'print',
        fabric : 'lawn',
        color : 'black',
        type : 'embroidered',
        season : 'winter',
        rating : 3.5,
        img1 : '/assests/images/prints/printedBlackFront.jpg',
        img2 : '/assests/images/prints/printedBlackBack.jpg',
        img3 : '/assests/images/prints/printedBlackSide.jpg',
        img4 : '/assests/images/prints/printedBlackZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 20,
        name : 'printed',
        price : 10000,
        category : 'print',
        fabric : 'karandi',
        color : 'green',
        type : 'printed',
        season : 'winter',
        rating : 4.7,
        img1 : '/assests/images/prints/printedGreenFront.jpg',
        img2 : '/assests/images/prints/printedGreenBack.jpg',
        img3 : '/assests/images/prints/printedGreenZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
];
