export const FilterData = [
    {
        price : [1000,2000,3000,4000,5000,6000,7000,8000,9000,10000],
        color : ["green","black","pink","white","blue", "orange"],
        type : ['printed','embroidered','plain'],
        fabric : ['karandi', 'lawn','cotton','chiffon','cambric','irish'],
        season : ['summer', 'winter','spring','eid special'],
    },
]

export const ProductData = [
    {
        id: 1,
        name : 'shadow work',
        price : '1000',
        category : 'casual',
        fabric : 'lawn',
        color : 'aqua',
        type : 'embroidered',
        season : 'summer',
        rating : 3,
        img1 : '/assests/images/casuals/shadowWorkAquaFront.jpg',
        img2 : '/assests/images/casuals/shadowWorkAquaBack.jpg',
        img3 : '/assests/images/casuals/shadowWorkAquaSide.jpg',
        img4 : '/assests/images/casuals/shadowWorkAquaZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 2,
        name : 'arezu range',
        price : '2000',
        category : 'casual',
        fabric : 'chiffon',
        color : 'black',
        type : 'printed',
        season : 'summer',
        rating : 3.4,
        img1 : '/assests/images/casuals/arezuRangeBlackFull.jpg',
        img2 : '/assests/images/casuals/arezuRangeBlackBack.jpg',
        img3 : '/assests/images/casuals/arezuRangeBlackSide.jpg',
        img4 : '/assests/images/casuals/arezuRangeBlackZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',
    },
    {
        id: 3,
        name : 'arezu range',
        price : '2000',
        category : 'casual',
        fabric : 'chiffon',
        color : 'white',
        type : 'printed',
        season : 'summer',
        rating : 3.6,
        img1 : '/assests/images/casuals/arezuWhiteFront.jpg',
        img2 : '/assests/images/casuals/arezuWhiteSide.jpg',
        img3 : '/assests/images/casuals/arezuWhiteZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 4,
        name : 'bahar gul',
        price : '3000',
        category : 'casual',
        fabric : 'cambric',
        color : 'blue',
        type : 'embroidered',
        season : 'summer',
        rating : 4,
        img1 : '/assests/images/casuals/baharGulBlueFull.jpg',
        img2 : '/assests/images/casuals/baharGulBlueBack.jpg',
        img3 : '/assests/images/casuals/baharGulBlueSide.jpg',
        img4 : '/assests/images/casuals/baharGulBlueZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 5,
        name : 'banjara',
        price : '4000',
        category : 'casual',
        fabric : 'lawn',
        color : 'orange',
        type : 'embroidered',
        season : 'summer',
        rating : 4.1,
        img1 : '/assests/images/casuals/banjaraOrangeFull.jpg',
        img2 : '/assests/images/casuals/banjaraOrangeback.jpg',
        img3 : '/assests/images/casuals/banjaraOrangeSide.jpg',
        img4 : '/assests/images/casuals/banjaraOrangeZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 6,
        name : 'botanic rhtym',
        price : '4000',
        category : 'casual',
        fabric : 'lawn',
        color : 'cream',
        type : 'plain',
        season : 'summer',
        rating : 4.5,
        img1 : '/assests/images/casuals/botanicCreamFull.jpg',
        img2 : '/assests/images/casuals/botanicCreamBack.jpg',
        img3 : '/assests/images/casuals/botanicCreamSide.jpg',
        img4 : '/assests/images/casuals/botanicCreamZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 7,
        name : 'chand bagh',
        price : '5000',
        category : 'casual',
        fabric : 'karandi',
        color : 'black',
        type : 'printed',
        season : 'winter',
        rating : 2.5,
        img1 : '/assests/images/casuals/chandBaghBlackFull.jpg',
        img2 : '/assests/images/casuals/chandBaghBlackSide.jpg',
        img3 : '/assests/images/casuals/chandBaghBlackZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 8,
        name : 'chand bagh',
        price : '5000',
        category : 'casual',
        fabric : 'karandi',
        color : 'blue',
        type : 'printed',
        season : 'winter',
        rating : 2.5,
        img1 : '/assests/images/casuals/chandBaghBlueFull.jpg',
        img2 : '/assests/images/casuals/chandBaghBlueBack.jpg',
        img3 : '/assests/images/casuals/chandBaghBlueSide.jpg',
        img4 : '/assests/images/casuals/chandBaghBlueZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 9,
        name : 'dolman range',
        price : '6000',
        category : 'casual',
        fabric : 'cotton',
        color : 'black',
        type : 'printed',
        season : 'spring',
        rating : 4.8,
        img1 : '/assests/images/casuals/dolmanRangeBlackFront.jpg',
        img2 : '/assests/images/casuals/dolmanRangeBlackBack.jpg',
        img3 : '/assests/images/casuals/dolmanRangeBlackSide.jpg',
        img4 : '/assests/images/casuals/dolmanRangeBlackZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 10,
        name : 'dolman',
        price : '6000',
        category : 'casual',
        fabric : 'cotton',
        color : 'black',
        type : 'printed',
        season : 'spring',
        rating : 4.8,
        img1 : '/assests/images/casuals/dolmenBlackfull.jpg',
        img2 : '/assests/images/casuals/dolmenBlack.jpg',
        img3 : '/assests/images/casuals/dolmenBlack2.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 11,
        name : 'dolman',
        price : '6000',
        category : 'casual',
        fabric : 'cotton',
        color : 'white',
        type : 'printed',
        season : 'spring',
        rating : 4.8,
        img1 : '/assests/images/casuals/dolmenWhiteFull.jpg',
        img2 : '/assests/images/casuals/dolmenWhiteSide.jpg',
        img3 : '/assests/images/casuals/dolmenWhiteZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 12,
        name : 'ethnic glow',
        price : '4000',
        category : 'casual',
        fabric : 'irish',
        color : 'black',
        type : 'embroidered',
        season : 'summer',
        rating : 4,
        img1 : '/assests/images/casuals/ethnicGlowBlackFull.jpg',
        img2 : '/assests/images/casuals/ethnicGlowBlackBack.jpg',
        img3 : '/assests/images/casuals/ethnicGlowBlackSide.jpg',
        img4 : '/assests/images/casuals/ethnicGlowBlackZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 13,
        name : 'ethnic glow',
        price : '4000',
        category : 'casual',
        fabric : 'irish',
        color : 'mustered',
        type : 'embroidered',
        season : 'summer',
        rating : 4,
        img1 : '/assests/images/casuals/ethnicGlowMusteredFull.jpg',
        img2 : '/assests/images/casuals/ethnicGlowMusteredBack.jpg',
        img3 : '/assests/images/casuals/ethnicGlowMusteredZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 14,
        name : 'flora garland',
        price : '6000',
        category : 'casual',
        fabric : 'cotton',
        color : 'blue',
        type : 'printed',
        season : 'eid special',
        rating : 4.8,
        img1 : '/assests/images/casuals/floraGarlandBlueFull.jpg',
        img2 : '/assests/images/casuals/floraGarlandBlueBack.jpg',
        img3 : '/assests/images/casuals/floraGarlandBlueSide.jpg',
        img4 : '/assests/images/casuals/floraGarlandBlueZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 15,
        name : 'glowing flora',
        price : '6000',
        category : 'casual',
        fabric : 'cotton',
        color : 'pink',
        type : 'printed',
        season : 'eid special',
        rating : 4.6,
        img1 : '/assests/images/casuals/glowingFloraPinkFull.jpg',
        img2 : '/assests/images/casuals/glowingFloraPinkBack.jpg',
        img3 : '/assests/images/casuals/glowingFloraPinkSide.jpg',
        img4 : '/assests/images/casuals/glowingFloraPinkZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 16,
        name : 'hangaria range',
        price : '7000',
        category : 'casual',
        fabric : 'lawn',
        color : 'blue',
        type : 'embroidered',
        season : 'summer',
        rating : 4.1,
        img1 : '/assests/images/casuals/hangriyanBlueFull.jpg',
        img2 : '/assests/images/casuals/hangriyanBlueBlack.jpg',
        img3 : '/assests/images/casuals/hangriyanBlueSide.jpg',
        img4 : '/assests/images/casuals/hangriyanBlueZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 17,
        name : 'shadow work',
        price : '4000',
        category : 'casual',
        fabric : 'lawn',
        color : 'green',
        type : 'embroidered',
        season : 'summer',
        rating : 4,
        img1 : '/assests/images/casuals/shadowWorkGreenFront.jpg',
        img2 : '/assests/images/casuals/shadowWorkGreenSide.jpg',
        img3 : '/assests/images/casuals/shadowWorkGreenZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 18,
        name : 'turkish flowers',
        price : '8000',
        category : 'casual',
        fabric : 'karandi',
        color : 'white',
        type : 'embroidered',
        season : 'winter',
        rating : 3.5,
        img1 : '/assests/images/casuals/turkishWhitefull.jpg',
        img2 : '/assests/images/casuals/turkishWhite.jpg',
        img3 : '/assests/images/casuals/turkishWhiteZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 19,
        name : 'turkish flowers',
        price : '10000',
        category : 'casual',
        fabric : 'karandi',
        color : 'white',
        type : 'embroidered',
        season : 'winter',
        rating : 3.5,
        img1 : '/assests/images/casuals/turkishWhiteFlower1.jpg',
        img2 : '/assests/images/casuals/turkishWhiteFlower2.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 20,
        name : 'vital range',
        price : 10000,
        category : 'casual',
        fabric : 'karandi',
        color : 'white',
        type : 'embroidered',
        season : 'winter',
        rating : 4.7,
        img1 : '/assests/images/casuals/vitalRangeWhiteFull.jpg',
        img2 : '/assests/images/casuals/vitalRangeWhiteBack.jpg',
        img3 : '/assests/images/casuals/vitalRangeWhiteSide.jpg',
        img4 : '/assests/images/casuals/vitalRangeWhiteZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },

   
];
