export const FilterData = [
    {
        price : [1000,2000,3000,4000,5000],
        color : ["black","green","red","white","beige","shocking pink"],
        type : ['embroidered'],
        fabric : ['cambric'],
        season : ['summer', 'eid special'],
    },
]


export const ProductData = [
    {
        id: 1,
        name : 'shisha work capri',
        price : '1000',
        category : 'bottom',
        fabric : 'cambric',
        color : 'black',
        type : 'embroidered',
        season : 'summer',
        rating : 3,
        img1 : '/assests/images/bottoms/BottomBlackFull.jpg',
        img2 : '/assests/images/bottoms/BottomBlackZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 2,
        name : 'shisha work capri',
        price : '2000',
        category : 'bottom',
        fabric : 'cambric',
        color : 'green',
        type : 'embroidered',
        season : 'summer',
        rating : 3.4,
        img1 : '/assests/images/bottoms/BottomGreenFull.jpg',
        img2 : '/assests/images/bottoms/BottomGreenZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',
    },
    {
        id: 3,
        name : 'shisha work capri',
        price : '2000',
        category : 'bottom',
        fabric : 'cambric',
        color : 'red',
        type : 'embroidered',
        season : 'summer',
        rating : 3.6,
        img1 : '/assests/images/bottoms/BottomRedFull.jpg',
        img2 : '/assests/images/bottoms/BottomRedZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 4,
        name : 'shisha work capri',
        price : '3000',
        category : 'bottom',
        fabric : 'cambric',
        color : 'white',
        type : 'embroidered',
        season : 'eid special',
        rating : 4,
        img1 : '/assests/images/bottoms/BottomWhiteFull.jpg',
        img2 : '/assests/images/bottoms/BottomWhiteZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 5,
        name : 'sleek 3',
        price : '4000',
        category : 'bottom',
        fabric : 'cambric',
        color : 'beige',
        type : 'embroidered',
        season : 'eid special',
        rating : 4.1,
        img1 : '/assests/images/bottoms/BottomBeigeFull.jpg',
        img2 : '/assests/images/bottoms/BottomBeigeZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 6,
        name : 'rangoli shalwar',
        price : '4000',
        category : 'bottom',
        fabric : 'cambric',
        color : 'shocking pink',
        type : 'embroidered',
        season : 'summer',
        rating : 4.5,
        img1 : '/assests/images/bottoms/BottomPink2.jpg',
        img2 : '/assests/images/bottoms/BottomPink1.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 7,
        name : 'rangoli shalwar',
        price : '5000',
        category : 'bottom',
        fabric : 'karandi',
        color : 'white',
        type : 'embroidered',
        season : 'summer',
        rating : 2.5,
        img1 : '/assests/images/bottoms/BottomWhite11.jpg',
        img2 : '/assests/images/bottoms/BottomWhite_11.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    }, 
];