export const FilterData = [
    {
        price : [1000,2000,3000,4000,5000,6000,7000,8000,9000,10000],
        color : ["mahroon","black","white","brown", "aqua", "red","beige","green","purple","grey"],
        type : ['embroidered','plain'],
        fabric : ["chiffon","net",'velvet'],
        season : ['summer', 'winter','spring','eid special'],
    },
]


export const ProductData = [
    {
        id: 1,
        name : 'afreen range',
        price : '1000',
        category : 'formal',
        fabric : 'chiffon',
        color : 'mahroon',
        type : 'embroidered',
        season : 'summer',
        rating : 4.1,
        img1 : '/assests/images/formals/afreenRangeMahroonFull.jpg',
        img2 : '/assests/images/formals/afreenRangeMahroonBack.jpg',
        img3 : '/assests/images/formals/afreenRangeMahroonSide.jpg',
        img4 : '/assests/images/formals/afreenRangeMahroonZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 2,
        name : 'antique jade',
        price : '2000',
        category : 'formal',
        fabric : 'net',
        color : 'black',
        type : 'embroidered',
        season : 'summer',
        rating : 3.4,
        img1 : '/assests/images/formals/antiqueJadeBlackFull.jpg',
        img2 : '/assests/images/formals/antiqueJadeBlackBack.jpg',
        img3 : '/assests/images/formals/antiqueJadeBlackSide.jpg',
        img4 : '/assests/images/formals/antiqueJadeBlackZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',
    },
    {
        id: 3,
        name : 'applique work',
        price : '2000',
        category : 'formal',
        fabric : 'velvet',
        color : 'white',
        type : 'embroidered',
        season : 'spring',
        rating : 3.0,
        img1 : '/assests/images/formals/appliqueWorkWhiteFull.jpg',
        img2 : '/assests/images/formals/appliqueWorkWhiteSide.jpg',
        img3 : '/assests/images/formals/appliqueWorkWhiteZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 4,
        name : 'applique work',
        price : '3000',
        category : 'formal',
        fabric : 'chiffon',
        color : 'white',
        type : 'embroidered',
        season : 'spring',
        rating : 4.6,
        img1 : '/assests/images/formals/appliqueWorkWhiteFull11.jpg',
        img2 : '/assests/images/formals/appliqueWorkWhiteBack.jpg',
        img3 : '/assests/images/formals/appliqueWorkWhiteSide11.jpg',
        img4 : '/assests/images/formals/appliqueWorkWhiteZoom11.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 5,
        name : 'badla work',
        price : '4000',
        category : 'formal',
        fabric : 'net',
        color : 'brown',
        type : 'embroidered',
        season : 'eid special',
        rating : 4.1,
        img1 : '/assests/images/formals/badlaWorkBrownFront.jpg',
        img2 : '/assests/images/formals/badlaWorkBrownBack.jpg',
        img3 : '/assests/images/formals/badlaWorkBrownSide.jpg',
        img4 : '/assests/images/formals/badlaWorkBrownZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 6,
        name : 'badla work',
        price : '4000',
        category : 'formal',
        fabric : 'net',
        color : 'red',
        type : 'embroidered',
        season : 'winter',
        rating : 4.5,
        img1 : '/assests/images/formals/badlaWorkRedFull.jpg',
        img2 : '/assests/images/formals/badlaWorkRedBack.jpg',
        img3 : '/assests/images/formals/badlaWorkRedSide.jpg',
        img4 : '/assests/images/formals/badlaWorkRedZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 7,
        name : 'festive harmony',
        price : '5000',
        category : 'formal',
        fabric : 'chiffon',
        color : 'red',
        type : 'plain',
        season : 'spring',
        rating : 2.5,
        img1 : '/assests/images/formals/festiveHarmonyRedFull.jpg',
        img2 : '/assests/images/formals/festiveHarmonyRedBack.jpg',
        img3 : '/assests/images/formals/festiveHarmonyRedSide.jpg',
        img3 : '/assests/images/formals/festiveHarmonyRedZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 8,
        name : 'flora vintage',
        price : '5000',
        category : 'formal',
        fabric : 'net',
        color : 'beige',
        type : 'embroidered',
        season : 'winter',
        rating : 2.5,
        img1 : '/assests/images/formals/floraVintageFull.jpg',
        img2 : '/assests/images/formals/floraVintageZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 9,
        name : 'gota work',
        price : '6000',
        category : 'formal',
        fabric : 'chiffon',
        color : 'green',
        type : 'embroidered',
        season : 'spring',
        rating : 4.8,
        img1 : '/assests/images/formals/gotaWorkGreenFull.jpg',
        img2 : '/assests/images/formals/gotaWorkGreenBack.jpg',
        img3 : '/assests/images/formals/gotaWorkGreenSide.jpg',
        img4 : '/assests/images/formals/gotaWorkGreenZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 10,
        name : 'gull noor',
        price : '6000',
        category : 'formal',
        fabric : 'velvet',
        color : 'green',
        type : 'embroidered',
        season : 'spring',
        rating : 4.8,
        img1 : '/assests/images/formals/gullNoorGreenFull.jpg',
        img2 : '/assests/images/formals/gullNoorGreenBack.jpg',
        img3 : '/assests/images/formals/gullNoorGreenSide.jpg',
        img3 : '/assests/images/formals/gullNoorGreenZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 11,
        name : 'gull noor',
        price : '6000',
        category : 'formal',
        fabric : 'chiffon',
        color : 'purple',
        type : 'plain',
        season : 'spring',
        rating : 4.8,
        img1 : '/assests/images/formals/gullNoorPurpleFull.jpg',
        img2 : '/assests/images/formals/gullNoorPurpleBack.jpg',
        img3 : '/assests/images/formals/gullNoorPurpleSide.jpg',
        img3 : '/assests/images/formals/gullNoorPurpleZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 12,
        name : 'mari gold',
        price : '4000',
        category : 'formal',
        fabric : 'net',
        color : 'beige',
        type : 'embroidered',
        season : 'summer',
        rating : 4,
        img1 : '/assests/images/formals/mariGoldBeigeFull.jpg',
        img2 : '/assests/images/formals/mariGoldBeigeBack.jpg',
        img3 : '/assests/images/formals/mariGoldBeigeSide.jpg',
        img4 : '/assests/images/formals/mariGoldBeigeZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 13,
        name : 'mari gold',
        price : '4000',
        category : 'formal',
        fabric : 'chiffon',
        color : 'green',
        type : 'embroidered',
        season : 'summer',
        rating : 4,
        img1 : '/assests/images/formals/mariGoldGreenFull.jpg',
        img2 : '/assests/images/formals/mariGoldGreenBack.jpg',
        img3 : '/assests/images/formals/mariGoldGreenSide.jpg',
        img3 : '/assests/images/formals/mariGoldGreenZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 14,
        name : 'noor rang',
        price : '6000',
        category : 'formal',
        fabric : 'chiffon',
        color : 'beige',
        type : 'embroidered',
        season : 'eid special',
        rating : 4.8,
        img1 : '/assests/images/formals/noorRangBeigeFull.jpg',
        img2 : '/assests/images/formals/noorRangBeigeBack.jpg',
        img3 : '/assests/images/formals/noorRangBeigeSide.jpg',
        img4 : '/assests/images/formals/noorRangBeigeZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 15,
        name : 'noor rang',
        price : '6000',
        category : 'formal',
        fabric : 'chiffon',
        color : 'green',
        type : 'embroidered',
        season : 'eid special',
        rating : 4.6,
        img1 : '/assests/images/formals/noorRangGreenFull.jpg',
        img2 : '/assests/images/formals/noorRangGreenBack.jpg',
        img3 : '/assests/images/formals/noorRangGreenSide.jpg',
        img4 : '/assests/images/formals/noorRangGreenZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 16,
        name : 'noor zindagi',
        price : '7000',
        category : 'formal',
        fabric : 'chiffon',
        color : 'grey',
        type : 'embroidered',
        season : 'summer',
        rating : 4.1,
        img1 : '/assests/images/formals/noorZandgiGreyFull.jpg',
        img2 : '/assests/images/formals/noorZandgiGreyBack.jpg',
        img3 : '/assests/images/formals/noorZandgiGreySide.jpg',
        img4 : '/assests/images/formals/noorZandgiGreyZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 17,
        name : 'noor zindagi',
        price : '4000',
        category : 'formal',
        fabric : 'net',
        color : 'grey',
        type : 'embroidered',
        season : 'summer',
        rating : 4,
        img1 : '/assests/images/formals/noorZandgiGreyFull11.jpg',
        img2 : '/assests/images/formals/noorZandgiGreyBack11.jpg',
        img3 : '/assests/images/formals/noorZandgiGreySide11.jpg',
        img3 : '/assests/images/formals/noorZandgiGreyZoom11.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 18,
        name : 'phool rho',
        price : '8000',
        category : 'formal',
        fabric : 'chiffon',
        color : 'red',
        type : 'embroidered',
        season : 'winter',
        rating : 3.5,
        img1 : '/assests/images/formals/phoolRhoRedFull.jpg',
        img2 : '/assests/images/formals/phoolRhoRedBack.jpg',
        img3 : '/assests/images/formals/phoolRhoRedSide.jpg',
        img3 : '/assests/images/formals/phoolRhoRedZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 19,
        name : 'radiant rang',
        price : '10000',
        category : 'formal',
        fabric : 'velvet',
        color : 'aqua',
        type : 'embroidered',
        season : 'winter',
        rating : 3.5,
        img1 : '/assests/images/formals/radiantRangAquaFull.jpg',
        img2 : '/assests/images/formals/radiantRangAquaBack.jpg',
        img2 : '/assests/images/formals/radiantRangAquaSide.jpg',
        img2 : '/assests/images/formals/radiantRangAquaZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },
    {
        id: 20,
        name : 'zardoi',
        price : 10000,
        category : 'formal',
        fabric : 'chiffon',
        color : 'black',
        type : 'embroidered',
        season : 'winter',
        rating : 4.7,
        img1 : '/assests/images/formals/zardoiBlackFull.jpg',
        img2 : '/assests/images/formals/zardoiBlackBack.jpg',
        img3 : '/assests/images/formals/zardoiBlackSide.jpg',
        img4 : '/assests/images/formals/zardoiBlackZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',

    },

   
];