export const FilterData = [
    {
        price : [1000,2000,3000,4000,5000,6000,7000,8000,9000,10000],
        color : ["green","white","black","beige","navy blue","off white","blue"],
        type : ['embroidered'],
        fabric : ['karandi', 'lawn','net','velvet'],
        season : ['summer', 'winter'],
    },
]


export const ProductData = [
    {
        id: 1,
        name : 'net applique shawl',
        price : '2000',
        category : 'shawl',
        fabric : 'lawn',
        color : 'white',
        type : 'embroidered',
        season : 'summer',
        img1 : '/assests/images/shawls/ShawlWhiteFull.jpg',
        img2 : '/assests/images/shawls/ShawlWhiteZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',
    },
    {
        id: 2,
        name : 'gull-e-lala shawl',
        price : '4000',
        category : 'shawl',
        fabric : 'lawn',
        color : 'black',
        type : 'embroidered',
        season : 'winter',
        img1 : '/assests/images/shawls/ShawlBlackFull11.jpg',
        img2 : '/assests/images/shawls/ShawlBlackZoom11.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',
    },
    {
        id: 3,
        name : 'net applique shawl',
        price : '10000',
        category : 'shawl',
        fabric : 'lawn',
        color : 'black',
        type : 'embroidered',
        season : 'summer',
        img1 : '/assests/images/shawls/ShawlBlackFull.jpg',
        img2 : '/assests/images/shawls/ShawlBlackZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',
    },
    {
        id: 4,
        name : 'ethic legacy shawl',
        price : '8000',
        category : 'shawl',
        fabric : 'velvet',
        color : 'beige',
        type : 'embroidered',
        season : 'summer',
        img1 : '/assests/images/shawls/ShawlBeigeFull.jpg',
        img2 : '/assests/images/shawls/ShawlBeigeZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',
    },
    {
        id: 5,
        name : 'tribal fusion shawl',
        price : '5000',
        category : 'shawl',
        fabric : 'velvet',
        color : 'navy blue',
        type : 'embroidered',
        season : 'winter',
        img1 : '/assests/images/shawls/ShawlNavyBlueFull.jpg',
        img2 : '/assests/images/shawls/ShawlNavyBlueZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',
    },
    {
        id: 6,
        name : 'golden empire shawl',
        price : '9000',
        category : 'shawl',
        fabric : 'karandi',
        color : 'black',
        type : 'embroidered',
        season : 'winter',
        img1 : '/assests/images/shawls/ShawlBlackFull22.jpg',
        img2 : '/assests/images/shawls/ShawlBlackZoom22.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',
    },
    {
        id: 7,
        name : 'red rose shawl',
        price : '1000',
        category : 'shawl',
        fabric : 'net',
        color : 'off white',
        type : 'embroidered',
        season : 'summer',
        img1 : '/assests/images/shawls/ShawlOffWhiteFull.jpg',
        img2 : '/assests/images/shawls/ShawlOffWhiteZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',
    },
    {
        id: 8,
        name : 'calor pick shawl',
        price : '6000',
        category : 'shawl',
        fabric : 'lawn',
        color : 'blue',
        type : 'embroidered',
        season : 'summer',
        img1 : '/assests/images/shawls/ShawlBlueFull11.jpg',
        img2 : '/assests/images/shawls/ShawlBlueZoom11.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',
    },
    {
        id: 9,
        name : 'kani bagh shawl',
        price : '2000',
        category : 'shawl',
        fabric : 'lawn',
        color : 'beige',
        type : 'embroidered',
        season : 'winter',
        img1 : '/assests/images/shawls/ShawlBeigeFull11.jpg',
        img2 : '/assests/images/shawls/ShawlBeigeZoom11.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',
    },
    {
        id: 10,
        name : 'sher shah shawl',
        price : '7000',
        category : 'shawl',
        fabric : 'velvet',
        color : 'green',
        type : 'embroidered',
        season : 'summer',
        img1 : '/assests/images/shawls/ShawlGreenFull.jpg',
        img2 : '/assests/images/shawls/ShawlGreenZoom.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',
    },
    {
        id: 11,
        name : 'nakkashi range shawl',
        price : '3000',
        category : 'shawl',
        fabric : 'karandi',
        color : 'beige',
        type : 'embroidered',
        season : 'summer',
        img1 : '/assests/images/shawls/ShawlBeigeFull22.jpg',
        img2 : '/assests/images/shawls/ShawlBeigeZoom22.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',
    },
    {
        id: 12,
        name : 'fusion art shawl',
        price : '10000',
        category : 'shawl',
        fabric : 'lawn',
        color : 'beige',
        type : 'embroidered',
        season : 'summer',
        img1 : '/assests/images/shawls/ShawlBeigeFull33.jpg',
        img2 : '/assests/images/shawls/ShawlBeigeZoom33.jpg',
        description : 'lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text lorem ipsum is not a dummy text',
    },
];
